### ISSUE TITLE
Links are not clickable when they are within the side progress bar

### ISSUE THREAD

**Issue by ch-lee** [forestryio/hugo-theme-novela#15]
Just wanted to start off by saying thanks for sharing this great theme.

Really awesome!

I think there is a slight issue with the side progress bar. If you have a post with links/anchor tags they don't seem to be clickable?

See screenshots:

<img width="1261" alt="not clickable" src="https://user-images.githubusercontent.com/3100303/72218731-167cb880-3536-11ea-98fc-00b96dc9350d.png">

If it's outside, it seems to be okay:

<img width="1162" alt="clickable" src="https://user-images.githubusercontent.com/3100303/72218735-21cfe400-3536-11ea-9ed4-38e70ffd8427.png">

Unfortunately, my css is bit weak in this area, not sure if it's a z-index or something?

Thanks

**Comment by DirtyF** [comment]
Fixed in #17
