### ISSUE TITLE
Tags Taxonomy Support

### ISSUE THREAD

**Issue by Richie94** [forestryio/hugo-theme-novela#23]
Hey there, 
just discovered Hugo today and i pretty much like this theme. But I miss support for tag taxonomy, so that I can access a /tags/xxx site and only retrieve the articles that have this tag. 
Because I have so far no knowledge, is this easy to add or does this require some deeper Hugo knowledge? At least for me it not seems so straight to copy the authors logic and transform it to tags...

**Comment by DirtyF** [comment]
Please refer to Hugo documentation or ask for help on Hugo's forum.
We don't intend to add any more feature to this theme.
