### ISSUE TITLE
Open Graph picture does not render when pasting link of the homepage in to facebook or email

### ISSUE THREAD

**Issue by craftsmandigital** [forestryio/hugo-theme-novela#25]
Open Graph picture does not render when pasting link of the homepage in to facebook or email

Onely a black rectangle as picture

on the other hand it works excelent on article pages

**Comment by DirtyF** [comment]
Hey, how did you set your open graph image?

To specify it for the homepage  add  `seo.image` in `_index.md`:

```yaml
seo:
  image: /images/hero-2.jpg
```

**Comment by DirtyF** [comment]
fixed in https://github.com/forestryio/hugo-theme-novela/commit/0c1c6cd137830d01bd6c14d63696fe7941131e57
