### ISSUE TITLE
Progress Bar Still Blocking Some Links, Subscribe Button Messed Up and Overriding Query

### ISSUE THREAD

**Issue by stephenajulu** [forestryio/hugo-theme-novela#27]
Found a "solution" for the first one ( #26 ) through Netlify's snippet injection (before </head> or </body>). 

The only issues i have now is the progress bar is still blocking **some** links ( #15 ), the subscribe button for the newsletter is messed up in mobile ( #7 ) https://github.com/forestryio/hugo-theme-novela/issues/7#issuecomment-569804407 and if i do override the theme's footer and add a few things to the one you already have will i need to copy your socials as well or will it look for it in mine(and not find it) and use yours?

Also if i were to add a menu, how would i go about it? Preferably an icon menu, for example a profile(for the about page) svg next to the link and dark/light mode switch. I know you said you are following the original theme but am not asking for a change am merely asking for advice and a bit of code if possible on how to implement this on my site.

Kindly Help Me

![Screen Shot 2020-04-03 at 13 16 54](https://user-images.githubusercontent.com/42298053/78350319-ac603680-75ad-11ea-930e-4076cc2e9a87.png)

**Comment by DirtyF** [comment]
Hey, sorry but we don't intend to provide support on this theme, we'll fix the mobile issues though.
