### ISSUE TITLE
Unreadable About page in dark mode

### ISSUE THREAD

**Issue by joekroese** [forestryio/hugo-theme-novela#29]
If you view the About page in dark mode, the font color for the bottom paragraph is too dark to be legible. The font color doesn't change with scrolling either.

https://hugo-novela-forestry.netlify.com/about/

**Comment by DirtyF** [comment]
Hey thanks for reporting, I'm not sure if that about page is even supposed to exists.

Original https://novela.narative.co theme does not seem to have one.
