### ISSUE TITLE
posts are not shown on the home page

### ISSUE THREAD

**Issue by davxiao** [forestryio/hugo-theme-novela#35]
Rookie question here.

I've added the submodule. The theme is applied but the posts are not coming up on the home page.  For example, `content/posts/my-first-post.md` is not there. 

I was using `ananke` theme before, the posts are there. I'm sure something is missing but couldn't figure out, thanks for your help! 

Using: Hugo v0.70.0

**Comment by DirtyF** [comment]
Novela is working fine with Hugo 0.70.0

![hugo-novela-070](https://user-images.githubusercontent.com/103008/81555205-75d5c280-9388-11ea-8c41-55cb008cf4c0.jpg)

Please reach out to Hugo's community if you need help with setting up a theme.

**Comment by robertvb** [comment]
Hi @DirtyF , I am having exactly the same issue, posts are created under /posts/ and marked as non draft but they are not visible. I have previous experience with other Hugo themes but never seen this before. Tested on Hugo v0.70 and v0.72. 

Maybe I am missing something? I have set up a repo: https://github.com/robertvb/test-novela

**Comment by DirtyF** [comment]
https://github.com/forestryio/novela-hugo-starter/blob/master/config.yaml

**Comment by DustinJSilk** [comment]
Did anyone find a solution to this?
My config matches the example, the only posts that show up are under the `content/post/` directory. No other directory works

**Comment by DustinJSilk** [comment]
I found the problem: you need to add a `type: post` to each articles meta data
