### ISSUE TITLE
Question: What is the hero section/partial?

### ISSUE THREAD

**Issue by sranvir** [forestryio/hugo-theme-novela#36]
Hello!
I am trying to port the theme for personal site, and I am a complete novice when it comes to UI/UX can somebody tell me what is the purpose of hero.html is it meant to represent the authors, or is there a different reasoning behind the 'hero' nomenclature? I have seen it a bunch of time, but there are other files too like authors, bio, etc, hence the confusion.

Sorry if the question is too vague. I am trying to trim out any excess bit of code that a personal blog, like mine, would not require and learn a little bit of web dev on the way. Any documentation you folks can link me to would be really awesome as well.

P.S: Thank you for an amazing theme

**Comment by DirtyF** [comment]
A hero is a distinguishable block, usually displayed with a large font that contains an article header and metadata. 

![Capture d’écran 2020-05-14 à 11 03 40](https://user-images.githubusercontent.com/103008/81915452-e2dc9880-95d2-11ea-9344-60d16c8da148.png)

See the corresponding partial: https://github.com/forestryio/hugo-theme-novela/blob/master/layouts/partials/page/hero.html
