### ISSUE TITLE
Guidelines for changing logo

### ISSUE THREAD

**Issue by Asasim08** [forestryio/hugo-theme-novela#37]
Is it possible to include specific guidelines for the creation and implementation of the .svg logo? 
I'm having a hard time changing it properly: adding "class="change-fill"" doesn't seem working for me.

Thanks in advance to everyone!

![logo-not-changing](https://user-images.githubusercontent.com/65369889/82669564-f5db1280-9c3b-11ea-9387-7909ec2464a1.jpg)

**Comment by DirtyF** [comment]
see README

**Comment by stephenajulu** [comment]
if change fill isn't working try style="fill: var(--primary);"
it didn't work for me too despite doing exactly what it said in the readme, but the above inline css should work try placing it before d="M298..."
so <path style="fill:var(--primary);" d="M29,8...."/>
