### ISSUE TITLE
authors articleList

### ISSUE THREAD

**Issue by lbliii** [forestryio/hugo-theme-novela#45]
Hey! First, love your theme. It's awesome. Thanks for making it.

I'm having trouble getting the author to populate on the main page and also on the author's bio page, the articleList associated with that author doesn't populate. I could be doing something wrong but just wanted to make sure. Currently using Hugo v0.74.3/extended. Using your theme [here](https://github.com/lbliii/lbeezr), if that's helpful.

**Comment by DirtyF** [comment]
Hope  you managed to fix it since, it works fine on my end.
