### ISSUE TITLE
Images not responsive

### ISSUE THREAD

**Issue by stephenajulu** [forestryio/hugo-theme-novela#54]
#28 
Having issues with image "overflowing" from the page contents
![Screenshot_2020-08-30 How to Create a Simple Personal URL Shortener with GitHub, Netlify and an Affordable Domain Name Ajul](https://user-images.githubusercontent.com/42298053/91661756-9e73fa80-eae6-11ea-8e97-fa25bf899a9f.png)

Other occurrences
![Screenshot_2020-08-30 How to Create a Dev Environment in Windows 10 Part 1 Ajulu's Blog](https://user-images.githubusercontent.com/42298053/91661807-e7c44a00-eae6-11ea-9901-664cfd8ce883.png)

**Comment by DirtyF** [comment]
Fixed in #50
