### ISSUE TITLE
Not compatible with quick start guide and Hugo v0.75.1

### ISSUE THREAD

**Issue by olsnacky** [forestryio/hugo-theme-novela#55]
### Observed Outcome
Following the quick start guide results in empty content when navigating to the entry point of the site.
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/7479776/94323802-83f44a80-ffda-11ea-8c21-c91201dc6fb8.png">

I have included a test post:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/7479776/94324097-a5096b00-ffdb-11ea-962a-7f8a4801e53d.png">

This is my `config.toml`:
```
baseURL = "https://blog.poxon.dev/"
languageCode = "en-au"
title = "David Poxon's Blog"
theme = "novela"
```
### Expected Outcome
There would be at least one post

**Comment by DirtyF** [comment]
👉 https://github.com/forestryio/novela-hugo-starter

**Comment by DirtyF** [comment]
@olsnacky If you want to start from the command line

### Quick Start

```
hugo new site blog-novela
cd blog-novela
hugo mod init
```

Add theme settings to your `config.toml`

```
# Theme settings
theme = "github.com/forestryio/hugo-theme-novela"

paginate = 6.0

[social]
twitter = "#"
github = "#"
instagram = "#"
linkedin = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"
```

# Create a first post
hugo new post/modules-hugo.md

# Preview draft post
hugo server -D

**Comment by olsnacky** [comment]
@DirtyF Thank you! Yes, I'm using Hugo's quick start.
