### ISSUE TITLE
mobile theme not working properly

### ISSUE THREAD

**Issue by sanvit** [forestryio/hugo-theme-novela#7]
When viewing from smartphones (Samsung Galaxy S8+, Galaxy Note 9), the desktop layout shows up instead of the mobile layout.
![photo_2019-12-25_00-06-07](https://user-images.githubusercontent.com/4323051/71417750-63ddd680-26aa-11ea-85ec-e1887949d97e.jpg)

**Comment by DirtyF** [comment]
Can you test on https://novela.narative.co/ ? Is it the same?

**Comment by sanvit** [comment]
This one works fine

**Comment by sanvit** [comment]
![Screenshot_20191225-015755_Chrome](https://user-images.githubusercontent.com/4323051/71420696-fdf94b00-26b9-11ea-887a-f59bd4682360.jpg)

I assume this one is the original (un-ported) version?

**Comment by gianlucahmd** [comment]
Works with me but the subscribe button is messed up:
<img width="454" alt="Screen Shot 2019-12-30 at 22 40 02" src="https://user-images.githubusercontent.com/16074217/71601825-7bf3a100-2b55-11ea-8c30-b2f762f8f17a.png">

**Comment by DirtyF** [comment]
@regisphilibert My bad, I didn't test the theme on mobile originally, is that something that looks like an eassy fix for TND?

**Comment by stephenajulu** [comment]
Yea my subscribe button is also messed up.

**Comment by regisphilibert** [comment]
@DirtyF sorry I missed this mention it seems. We'll look into it.
