### ISSUE TITLE
where do i find icons?

### ISSUE THREAD

**Issue by stephenajulu** [forestryio/hugo-theme-novela#73]
Hi, how are you?
I recently added a menu, but the design was ruined as the icon looked out of place, where did you find those icons, i need one for menu. Tried fontawesome but it didn't look flush.

Another issue is that, each time i write a new post. It comes out as a toml instead of yaml and image path is wrong "/static/images/image.jpg" instead of "/images/image.jpg". 
The file ends up looking like

+++title = "Title" image ="/static/images/image.jpg".........................................+++

**Comment by DirtyF** [comment]
The original theme has some icons but does not seem to rely on any library:
https://github.com/narative/gatsby-theme-novela/tree/master/@narative/gatsby-theme-novela/src/icons/ui
