### ISSUE TITLE
How to change font for headings and body

### ISSUE THREAD

**Issue by stephenajulu** [forestryio/hugo-theme-novela#77]
Hi, how do I change the font of the body and heading?
I want to use playfair(title) + libre baskerville(body)

**Comment by DirtyF** [comment]
See https://github.com/forestryio/hugo-theme-novela/blob/master/assets/scss/vars.scss#L12-L14

Copy this file to your project in `/assets/scss/vars.scss` to override the theme, change the values in your file.

**Comment by stephenajulu** [comment]
body{
    /*FONTS*/
    --serif: "Playfair Display", Georgia, Serif;
    --sanserif: "Libre Baskerville", "SF Pro Display", "-apple-system", "BlinkMacSystemFont", "San Francisco", "Helvetica Neue", "Helvetica", "Ubuntu", "Roboto", "Noto", "Segoe UI", "Arial", sans-serif;
    --monospace: "Operator Mono", Consolas, Menlo, Monaco, source-code-pro, Courier New, monospace;


did as you said but it's still using the previous

**Comment by DirtyF** [comment]
This theme only use System fonts by default, If you use Google Web fonts, you also need to import those fonts in the head, e.g:

```html
<style>
 @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Playfair+Display&display=swap');
</style> 
```

**Comment by stephenajulu** [comment]
thank you
