### ISSUE TITLE
Create a category list page.

### ISSUE THREAD

**Issue by kerry-tokyo** [forestryio/hugo-theme-novela#8]
Hi,
Thanks for creating a great theme!
I want to display the category list page, but it doesn't work.
For example,
novela.com/categories/orange/
novela.com/categories/red/

I want to display articles with each category when I access the permalink as above.

Do you plan to introduce category features in the future?
This is a great theme and I don't want to change it if possible.

**Comment by DirtyF** [comment]
Hi, glad you like it. 

We don't plan to add any other feature from the original theme at https://novela.narative.co

I don't see why you wouldn't be able to override the theme and use a category list template.

**Comment by shinzo-tokyo** [comment]
/ Category / orange /
When accessed, the same article as the home page, that is, all articles will be displayed.

I'll give it a try.
